#██████      ██████         ██ 
#██   ██     ██   ██        ██ 
#██████      ██████         ██ 
#██          ██   ██        ██ 
#██ ██       ██   ██ ██     ██ ██
#Players     Require        Items

#INFORMAZIONI PER IL PLUGIN, NON TOCCARE!
#----------------------------------------
Version: 1.0.0
#----------------------------------------


